### ISSUE TITLE
some ldf keys in boot.cfg are non-configurable

### ISSUE THREAD

**Issue by EmosewaMC** [I-Am-Dench/nimbus-launcher#19]
https://github.com/I-Am-Dench/nimbus-launcher/blob/main/ldf/boot.go#L16-L19

the above 4 keys are not configurable in the client and are hard coded strings within the executable.  Just thought i'd let you know in case you noticed that changing these did nothing for some reason :)

I don't work in go at this time so I wont put a pr in myself but ill leave this here as a note.

**Comment by I-Am-Dench** [comment]
Yes, I did notice! It's a bit unfortunate that they don't do anything within the actual client, I mostly left them in for consistency like the `DATACENTERID` and `TRACK_DSK_USAGE` fields (not actually sure if the client uses them. I haven't really done a whole lot of research into it) so that if someone DID want to edit them then they could do so within the launcher, but at the very least I was able to repurpose them for links on the launcher itself (i.e. having link to the Nexus Dashboard login).

There is an argument to be had about removing the Register and Reset Password fields, so I'll leave this issue open. Might be something to consider for at the latest version 1.0.0.

**Comment by I-Am-Dench** [comment]
Thanks, that makes sense. Though, I was more referring to just examples of fields that don't necessarily have a use at the moment, but are still configurable as they may have a use in the future. Maybe `AKAMAIDLM`, `CPCODE`, and `CRASHLOGURL` would have been better examples? The `DATACENTERID` and UGC configurations did, however, send me on a small tangent just to check that the launcher's usage of `PATCHSERVERIP` does not conflict with the client's usage of the field, which it doesn't appear to (that's good). 

Also, after sitting on it for a while, the URL fields will not be removed any time soon. Due to how `ldf.Marshal` works, removing the struct fields would delete them from `boot.cfg` upon subsequent saves, and my philosophy for handling client resources is to somewhat preserve how the client is/was. In this case, I want to make sure that if someone were to have those fields edited they won't just randomly get removed, even if they don't necessarily have an use besides being repurposed by the launcher.

This *could* potentially spin itself into a separate issue, as `boot_backup.cfg` includes `MANIFESTFILE`, `HD_SPACE_FREE`, and `HD_SPACE_USED`, so there is a case to be made for adding those fields so that they don't just disappear. `MANIFESTFILE`, however, screams "build artifact" to me (or maybe something to do with Akamai?), so it would only really be added once there is a well-known use case.
